server:
  port: 8080
spring:
  cloud: 
   gateway: 
    routes:
      - id: catalog
        uri: lb://catalog/
        predicates:
          - Path=/product/**
      - id: cart
        uri: lb://cart/
        predicates:
          - Path=/cart/**
